=== neoo23/diary-express/data/diary/diary-month.dtd
<!ELEMENT diary-month ( day* ) >
<!ELEMENT day ( kiten?, body, link* ) >

<!ELEMENT body ( p+ ) >
<!ELEMENT p ( #PCDATA ) >
<!ATTLIST p tag CDATA #IMPLIED >
<!ATTLIST p title CDATA #IMPLIED >

<!ATTLIST diary-month y CDATA #REQUIRED >
<!ATTLIST diary-month m CDATA #REQUIRED >

<!ELEMENT kiten EMPTY >
<!ATTLIST kiten title CDATA #REQUIRED >
<!ATTLIST kiten spot CDATA #REQUIRED >
<!ATTLIST kiten time CDATA #REQUIRED >
<!ATTLIST kiten boards CDATA #REQUIRED >
<!ATTLIST kiten kites CDATA #REQUIRED >
<!ATTLIST kiten wind CDATA #REQUIRED >
<!ATTLIST kiten fun CDATA #REQUIRED >

<!ATTLIST day title CDATA #REQUIRED >
<!ATTLIST day d CDATA #REQUIRED >

<!ELEMENT link ( #PCDATA ) >
<!ATTLIST link aref CDATA #REQUIRED >
<!ATTLIST link name CDATA #REQUIRED >

=== neoo23/diary-express/data/diary/2021-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE diary-month SYSTEM "http://localhost:8080/diary/doctypes/diary-month.dtd">
<!-- tags: mum, money, news, kiten, dinge, movie, game, family, friends, work, arzt, auto, sport, bad, buch, urlaub, garten, music, recap, graffiti, fpv, selfimpr, wowa, bike, wissen -->

<diary-month y="2021" m="01">

<!-- 01-->
<day d="01" title="The day after">
<body>
<p tag="family" title="what a mess at silvester"></p>
<p tag="movie" title="watched the witcher 101">
this show starts a little confusing, lets give it a chance</p>
</body></day>

<!-- 02-->
<day d="02" title="New work week">
<body>
<p tag="work" title="new week at cavana inc. - new office"></p>
<p tag="movie" title="watched the witcher 102"/>
</body></day>

<!-- 03-->
<day d="03" title="Got ill, damn it!">
<body>
<p tag="arzt" title="Got ill, damn it!"></p>
<p tag="movie" title="watched the witcher 103-108, bing watched"/>
</body></day>

</diary-month>
